name: Terraform From Secret

on:
  workflow_dispatch:
jobs:
  run-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Create working directory
        run: mkdir -p ./terraform

      - name: Decode Terraform file from secret
        run: echo "${{ secrets.TERRAFORM }}" | base64 --decode > ./terraform/main.tf

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
